name: CI Fuzz

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FUZZING_SERVER_ADDRESS: grpc.code-intelligence.com:443
  WEB_APP_ADDRESS: https://app.code-intelligence.com
  CHECKOUT_DIR: checkout-dir/


jobs:
  fuzz_tests:
    runs-on: ubuntu-latest
    container: cifuzz/builders:maven
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.CHECKOUT_DIR }}
      - id: install-build-tools
        name: Install Fuzzer Build Tools
        uses: CodeIntelligenceTesting/github-actions/install-fuzzer-builder@master
      - id: build-fuzzers
        name: Build Fuzzers
        run: |
          echo ${{ secrets.CI_FUZZ_API_TOKEN }} | cictl login -s ${{ env.FUZZING_SERVER_ADDRESS }}
          cictl list projects -s ${{ env.FUZZING_SERVER_ADDRESS }}
        shell: "bash"
